name: "Deployment"

on:
  push:
    branches:
      - "main"
    paths:
      - "terraform/**"
      - ".github/workflows/**"

jobs:
  tf_fmt:
    name: Validate Terraform formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check formatting of all Terraform files
        run: terraform fmt -check -diff -recursive
  test:
    name: Deploy to "Test"
    uses: ./.github/workflows/terraform.yml
    with:
      workdir: terraform/test
      apply: true
      apply_environment: test
    secrets: inherit
  staging:
    name: Deploy to "Staging"
    needs: test
    uses: ./.github/workflows/terraform.yml
    with:
      workdir: terraform/staging
      apply: true
      apply_environment: staging
    secrets: inherit
  production:
    name: Deploy to "Production"
    needs: staging
    uses: ./.github/workflows/terraform.yml
    with:
      workdir: terraform/production
      apply: true
      plan_environment: production
      apply_environment: production
    secrets: inherit
