name: "Validate and plan for pull request"

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/**"
  push:
    branches:
      - "main"
    paths:
      - "terraform/**"
      - ".github/workflows/**"

jobs:
  tf_fmt:
    name: Validate Terraform formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6
      - name: Check formatting of all Terraform files
        run: terraform fmt -check -diff -recursive
  tfsec:
    name: tfsec check
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: terraform/
          github_token: ${{ secrets.GITHUB_TOKEN }}
  plan_test:
    name: Test Terraform plan
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "eu-west-1"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6
      - name: Terraform init
        run: terraform init -input=false
        working-directory: terraform/test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_key }}
      - name: Terraform validate
        run: terraform validate
        working-directory: terraform/test
      - name: Terraform plan
        run: terraform plan -input=false -refresh=false -lock=false
        working-directory: terraform/test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_key }}
  plan_staging:
    name: Staging Terraform plan
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "eu-west-1"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6
      - name: Terraform init
        run: terraform init -input=false
        working-directory: terraform/staging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_key }}
      - name: Terraform validate
        run: terraform validate
        working-directory: terraform/staging
      - name: Terraform plan
        run: terraform plan -input=false -refresh=false -lock=false
        working-directory: terraform/staging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_key }}
  validate_production:
    name: Validate production Terraform config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6
      - name: Terraform init
        run: terraform init -input=false -backend=false
        working-directory: terraform/production
      - name: Terraform validate
        run: terraform validate
        working-directory: terraform/production
