name: "Deployment"

on:
  push:
    branches:
      - "main"
    paths:
      - "terraform/**"

jobs:
  plan_test:
    uses: ./.github/workflows/terraform.yml
    with:
      workdir: terraform/test
      apply: true
      environment: test
    secrets:
      access_key: ${{ secrets.access_key_dev }}
      secret_key: ${{ secrets.secret_key_dev }}
