name: "Testing self-hosted runner"

on:
  push:
    branches:
      - "DT-58"

jobs:
  test:
    name: "Check it's running"
    runs-on: self-hosted
    steps:
      - name: Check out CPM code
        uses: actions/checkout@v3
        with:
          repository: 'communitiesuk/common-payments-module'
          ref: 'develop'
      - run: echo "hello world"
        working-directory: marklogic