name: "Validate and plan for pull request"

on:
  pull_request:
    paths:
      - "terraform/**"

jobs:
  validate_test:
    uses: ./.github/workflows/terraform.yml
    with:
      workdir: test
    secrets:
      access_key: "${{secrets.access_key_dev}}"
      secret_key: "${{secrets.secret_key_dev}}"
  validate_staging:
    uses: ./.github/workflows/terraform.yml
    with:
      workdir: test
    secrets:
      access_key: "${{secrets.access_key_dev}}"
      secret_key: "${{secrets.secret_key_dev}}"
