name: "Roxy - Deploy MarkLogic config"

on:
  # Change from push to workflow_dispatch once merged (only available via website once on main branch)
  # workflow_dispatch:
  #   inputs:
  #     git_ref:
  #       description: 'Commit or branch to deploy'
  #       required: true
  #       type: string
  #     environment:
  #       description: 'Environment to run against'
  #       required: true
  #       type: environment

  push:
    branches:
      - "DT-58"

jobs:
  deploy_ml:
    name: "Deploy MarkLogic config"
    runs-on: ["self-hosted", "staging"] # ${{ inputs.environment }}
    needs: get_terraform_outputs
    environment: staging # ${{ inputs.environment }}
    env:
      # ml_* vars override Roxy's properties
      ml_dluhc_server: marklogic.vpc.local
      ml_ldap_password: ${{ secrets.CPM_LDAP_PASSWORD }}
      ml_password: ${{ secrets.CPM_ML_ADMIN_PASSWORD }}
    defaults:
      run:
        working-directory: marklogic
    steps:
      - name: Check out CPM code
        uses: actions/checkout@v3
        with:
          repository: "communitiesuk/common-payments-module"
          ref: DT-58 # ${{ inputs.git_ref }}
          token: ${{ secrets.GIT_PAT }} # TODO: create a dedicated Git account for this purpose?
      - run: chmod +x ./ml
      - run: ./ml dluhc bootstrap -v # --apply-changes=privileges,amps,indexes <--- unsure what the implications of this are
      - run: ./ml dluhc clean modules -v
      - run: ./ml dluhc clean schemas -v
      - run: ./ml dluhc deploy modules -v
      - run: ./ml dluhc deploy schemas -v
      # - run: ./ml dluhc deploy content <--- would deploy dummy data from the /data folder
